spring:
  application:
    name: url-query-service
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:${SERVICE_PORT:8888}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}
  datasource:
    url: jdbc:postgresql://${QUERY_DB_HOST:localhost}:${POSTGRES_PORT:5432}/${QUERY_DB_NAME:query_url_db}
    username: ${QUERY_DB_USER}
    password: ${QUERY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 2000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: query-pool
      data-source-properties:
        connectTimeout: 2
        socketTimeout: 3
        cancelSignalTimeout: 2
        tcpKeepAlive: true
        options: -c statement_timeout=1500 -c lock_timeout=1000 -c idle_in_transaction_session_timeout=2000
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  data:
    redis:
      host: ${QUERY_CACHE_HOST:localhost}
      port: ${QUERY_CACHE_PORT:6379}
      password: ${QUERY_CACHE_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
logging:
  level:
    root: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
