server:
  port: ${SERVICE_PORT:8080}
  shutdown: graceful
spring:
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 1000
            response-timeout: 5s
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:3000" # TODO
                allowedMethods:
                  - GET
                  - POST
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: url-command-service
              uri: lb://url-command-service
              predicates:
                - Path=/api/urls,/api/urls/**
                - Method=POST,DELETE
              metadata:
                response-timeout: 5000

            - id: url-query-service
              uri: lb://url-query-service
              predicates:
                - Path=/r/**
                - Method=GET
              metadata:
                response-timeout: 2000
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${SERVICE_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
