server:
  port: ${SERVICE_PORT:8080}
  shutdown: graceful
spring:
  cloud:
    circuitbreaker:
      resilience4j:
        disable-time-limiter: true
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 1000
            response-timeout: 5s
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
              cors-configurations:
                '[/**]':
                allowedOrigins: ${GATEWAY_ALLOWED_ORIGINS:http://localhost:3000}
                allowedMethods:
                  - GET
                  - POST
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
          routes:
            - id: url-command-service
              uri: lb://url-command-service
              predicates:
                - Path=/api/urls,/api/urls/**
                - Method=POST,DELETE
              filters:
                - name: CircuitBreaker
                  args:
                    name: urlCommandCircuitBreaker
                    fallbackUri: forward:/fallback/url-command-service
                    statusCodes:
                      - 500
                      - 502
                      - 503
                      - 504
              metadata:
                response-timeout: 5000

            - id: url-query-service
              uri: lb://url-query-service
              predicates:
                - Path=/r/**
                - Method=GET
              filters:
                - name: CircuitBreaker
                  args:
                    name: urlQueryCircuitBreaker
                    fallbackUri: forward:/fallback/url-query-service
                    statusCodes:
                      - 500
                      - 502
                      - 503
                      - 504
              metadata:
                response-timeout: 2000
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      urlCommandCircuitBreaker:
        baseConfig: default
      urlQueryCircuitBreaker:
        baseConfig: default
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${SERVICE_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
