server:
  port: ${INTERNAL_SERVICE_PORT:8080}
  shutdown: graceful
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  eureka:
    client:
      service-url:
        defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
      register-with-eureka: true
      fetch-registry: true
      registry-fetch-interval-seconds: 5
