server:
  port: ${SERVICE_PORT:8080}
  shutdown: graceful
spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
  transaction:
    default-timeout: 1500ms
  kafka:
    consumer:
      group-id: url-query-service-group
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        default.api.timeout.ms: 10000
        request.timeout.ms: 5000
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: "com.plema.url_query_service.domain.event"
        spring.json.use.type.headers: true
        spring.json.type.id.header: "eventType"
        spring.json.type.mapping: "created.v1:com.plema.url_query_service.domain.event.ShortUrlCreatedEvent,deleted.v1:com.plema.url_query_service.domain.event.ShortUrlDeletedEvent"
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        request.timeout.ms: 5000
        delivery.timeout.ms: 10000
        retry.backoff.ms: 500
        retry.backoff.max.ms: 5000
        spring.json.add.type.headers: true
        spring.json.type.mapping: "created.v1:com.plema.url_query_service.domain.event.ShortUrlCreatedEvent,deleted.v1:com.plema.url_query_service.domain.event.ShortUrlDeletedEvent"
    listener:
      ack-mode: manual_immediate
    retry:
      topic:
        enabled: true
        attempts: 4
        backoff:
          delay: 500ms
          multiplier: 2.0
          max-delay: 5s
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      timeout: 200ms
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${SERVICE_PORT:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
kafka:
  topics:
    short-url-events: plema.shorturl
  retry:
    topic:
      retry-suffix: -retry
      dlt-suffix: -dlt
      auto-create-topics: true
      num-partitions: 1
      replication-factor: 1
