server:
  port: ${SERVICE_PORT:8888}
  shutdown: graceful
spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${SERVICE_PORT:8761}/eureka/
    register-with-eureka: false
    fetch-registry: false