spring:
  application:
    name: url-command-service
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:${SERVICE_PORT:8888}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${POSTGRES_PORT:5432}/${CMD_DB_NAME:cmd_url_db}
    username: ${CMD_DB_USER}
    password: ${CMD_DB_PASSWORD}